[package]
name = "img2ascii"
version = "0.1.0"
authors = ["luisleee <luisleee@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
